/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["../views/**/*.html"],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: [
      {
        padel: {
          "primary": "#2D4356",
          "primary-content": "#FFFFFF",
          "secondary": "#3B5068",
          "secondary-content": "#FFFFFF",
          "accent": "#4ECDC4",
          "accent-content": "#1A2A36",
          "neutral": "#2D4356",
          "neutral-content": "#D5DDE5",
          "base-100": "#F8F9FA",
          "base-200": "#EFF1F3",
          "base-300": "#DEE2E6",
          "base-content": "#2D4356",
          "info": "#4ECDC4",
          "info-content": "#1A2A36",
          "success": "#45B7A0",
          "success-content": "#FFFFFF",
          "warning": "#E5B960",
          "warning-content": "#1A2A36",
          "error": "#E57373",
          "error-content": "#FFFFFF",
        },
      },
      {
        dark: {
          "primary": "#4ECDC4",
          "primary-content": "#1A2A36",
          "secondary": "#6C9BCF",
          "secondary-content": "#FFFFFF",
          "accent": "#4ECDC4",
          "accent-content": "#1A2A36",
          "neutral": "#2A303C",
          "neutral-content": "#C6D0DC",
          "base-100": "#1A2A36",
          "base-200": "#223344",
          "base-300": "#2D4356",
          "base-content": "#D5DDE5",
          "info": "#4ECDC4",
          "info-content": "#1A2A36",
          "success": "#45B7A0",
          "success-content": "#1A2A36",
          "warning": "#E5B960",
          "warning-content": "#1A2A36",
          "error": "#E57373",
          "error-content": "#1A2A36",
        },
      },
    ],
  },
}
