/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["../views/**/*.html"],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: [
      {
        padel: {
          "primary": "#0D9488",
          "primary-content": "#FFFFFF",
          "secondary": "#1E293B",
          "secondary-content": "#FFFFFF",
          "accent": "#F59E0B",
          "accent-content": "#1E293B",
          "neutral": "#1E293B",
          "neutral-content": "#E2E8F0",
          "base-100": "#F8FAFC",
          "base-200": "#F1F5F9",
          "base-300": "#E2E8F0",
          "base-content": "#0F172A",
          "info": "#0EA5E9",
          "info-content": "#FFFFFF",
          "success": "#22C55E",
          "success-content": "#FFFFFF",
          "warning": "#F59E0B",
          "warning-content": "#1E293B",
          "error": "#EF4444",
          "error-content": "#FFFFFF",
        },
      },
      {
        dark: {
          "primary": "#14B8A6",
          "primary-content": "#042F2E",
          "secondary": "#334155",
          "secondary-content": "#F8FAFC",
          "accent": "#FBBF24",
          "accent-content": "#1E293B",
          "neutral": "#1E293B",
          "neutral-content": "#CBD5E1",
          "base-100": "#0F172A",
          "base-200": "#1E293B",
          "base-300": "#334155",
          "base-content": "#E2E8F0",
          "info": "#38BDF8",
          "info-content": "#0C4A6E",
          "success": "#4ADE80",
          "success-content": "#052E16",
          "warning": "#FBBF24",
          "warning-content": "#1E293B",
          "error": "#F87171",
          "error-content": "#450A0A",
        },
      },
    ],
  },
}
