/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["../views/**/*.html"],
  plugins: [require("daisyui"), require("@tailwindcss/typography")],
  daisyui: {
    themes: [
      {
        padel: {
          "primary": "#B5D334",
          "primary-content": "#0B0B0B",
          "secondary": "#1E293B",
          "secondary-content": "#F8FAFC",
          "accent": "#B5D334",
          "accent-content": "#0B0B0B",
          "neutral": "#0B0B0B",
          "neutral-content": "#F8FAFC",
          "base-100": "#F8FAFC",
          "base-200": "#F1F5F9",
          "base-300": "#E2E8F0",
          "base-content": "#0F172A",
          "info": "#0EA5E9",
          "info-content": "#FFFFFF",
          "success": "#16A34A",
          "success-content": "#FFFFFF",
          "warning": "#D97706",
          "warning-content": "#FFFFFF",
          "error": "#DC2626",
          "error-content": "#FFFFFF",
        },
      },
      {
        dark: {
          "primary": "#B5D334",
          "primary-content": "#0B0B0B",
          "secondary": "#262626",
          "secondary-content": "#F8FAFC",
          "accent": "#B5D334",
          "accent-content": "#0B0B0B",
          "neutral": "#0B0B0B",
          "neutral-content": "#E2E8F0",
          "base-100": "#0B0B0B",
          "base-200": "#161616",
          "base-300": "#262626",
          "base-content": "#E2E8F0",
          "info": "#38BDF8",
          "info-content": "#0C4A6E",
          "success": "#4ADE80",
          "success-content": "#052E16",
          "warning": "#FBBF24",
          "warning-content": "#1E293B",
          "error": "#F87171",
          "error-content": "#450A0A",
        },
      },
    ],
  },
}
